### ISSUE TITLE
Plan 0.1.2

### ISSUE THREAD

**Issue by muga** [muga/embulk-filter-calcite#21]
- [x] Change with google style #14
- [x] Deduplicate Jdbc URL logging #16
- [x] Add 'options' option to configure JDBC properties #17
- [x] Add warning to change default of case sensitive #18
- [x] Upgrade Apache Calcite 1.12.0 #20

**Comment by muga** [comment]
Preparing v0.1.2 on https://github.com/muga/embulk-filter-calcite/pull/22
