### ISSUE TITLE
Plan 0.1.3

### ISSUE THREAD

**Issue by muga** [muga/embulk-filter-calcite#27]
- [x] Use PreparedStatement to improve the performance. #23
- [x] Deduplicate redundant logging to fix #24. #25
- [x] Add settings.gradle. #26

**Comment by muga** [comment]
Preparing 0.1.3 on https://github.com/muga/embulk-filter-calcite/pull/28
